### ISSUE TITLE
crash at 	m_code.resize(static_cast<size_t>(inf.max_ea - inf.min_ea));

### ISSUE THREAD

**Issue by Karaulov** [mwl4/ida_gcc_rtti#1]
`	m_code.resize(static_cast<size_t>(inf.max_ea - inf.min_ea));`
( size = 0xFF000000 )

python plugins work without problems) but slow speed. Please fix this plugin for ida 7.0 x64 32 (ida.exe)

target: mac os executable. (Objective-C)

**Comment by Karaulov** [comment]
After use "gcc rtti" all found data can be saved to decompiled source code ?

**Comment by mwl4** [comment]
Hello,

Some fixes have been pushed to the master branch (https://github.com/mwl4/ida_gcc_rtti/commit/40230d138544f07cc3d12f1d47022136f9d6874d)

Download new binaries and check again if it works.

GCC RTTI can be used to dump all classes to for example C++ code with bases, however this feature is not written yet, so either you will write it in your own fork, or you will wait for it. I am not sure what do you mean by "decompiled source code".

Cheers

**Comment by Karaulov** [comment]
Class informer for msvc can save all data to decompiled source?

Class informer for gcc can't do it ?

**Comment by Karaulov** [comment]
Impossible to rename functions/etc using found data ?

**Comment by Karaulov** [comment]
Plugin for IDA.exe (x64 32) not works!


**LoadLibrary(D:\IDA_Disassembler\plugins\gcc_rtti.dll) error: %1 Win32.**

**Comment by Karaulov** [comment]
And i got error: 

---------------------------
Warning
---------------------------
Code size exceeds limit of 100 MB (4157235199 MB)
---------------------------
OK   
---------------------------

As using inf.min_ea /max_ea

I don't know but any plugins using this values without problem.

**Comment by mwl4** [comment]
Check: https://github.com/mwl4/ida_gcc_rtti/commit/b5130111361f5295320db275e63a67b248e31337

I have added x64 versions (IDA 32 and 64), one x86 version (IDA 32). 

Check now if you get any warnings.

About renaming functions: it is possible to rename constructors/destructors, but there is no method to be 100% ensured that certain method is constructor or destructor. In many cases base constructors are inlined to child constructors, etc.

**Comment by Karaulov** [comment]
Now no error!

"0x00FD6470: over 100 base classes (13591600)(0x00FD647C)?!" - this is error ?

**Comment by mwl4** [comment]
Yes this is error. Check manually what is under 0x00FD647C and 0x00FD6470 address. Under first one there should be base count number, however it seems to be invalid data.

**Comment by mwl4** [comment]
It is bypassed by plugin, just some multi-base class is skipped in processing.

**Comment by Karaulov** [comment]
I got error "rename byte" "bad character" 

E5B6A0: can't rename byte as '__ZTS��' because it contains a bad character ''.
E5B680: can't rename byte as '__ZTI��' because it contains a bad character ''.
E5B6C0: can't rename byte as '__ZTS��' because it contains a bad character ''.
E5B6A0: can't rename byte as '__ZTI��' because it contains a bad character ''.
E5B760: can't rename byte as '__ZTS��' because it contains a bad character ''.
E5B740: can't rename byte as '__ZTI��' because it contains a bad character ''.

**Comment by Karaulov** [comment]
Binaries: 
[MacOS.zip](https://github.com/mwl4/ida_gcc_rtti/files/1778282/MacOS.zip)

**Comment by mwl4** [comment]
Check now: https://github.com/mwl4/ida_gcc_rtti/commit/098d2dea0c7b9ac5f6333106eef5ea558bd54b1f
