### ISSUE TITLE
Any interest in providing a build for IDA 7.7?

### ISSUE THREAD

**Issue by mzpqnxow** [mwl4/ida_gcc_rtti#3]
I'm not sure if this will build cleanly without modifications for IDA7.7 as I believe there were some backwards compatibility features hard-removed- but would you be willing to provide a build for IDA7.7 on win x64? Thanks for your work on this project!

**Comment by mwl4** [comment]
IDA 7.7 has built-in recognition GCC RTTI on all platforms I believe. Unless you need generating graph from classes, but that sounds like different plugin.

**Comment by mzpqnxow** [comment]
> IDA 7.7 has built-in recognition GCC RTTI on all platforms I believe. Unless you need generating graph from classes, but that sounds like different plugin.

You're correct from what I've seen, however I was curious as to what the comparison would be in terms of the output

Anyway, thanks for this project and for getting back to me
